export type TProject = {
  link: string;
  extraData: TExtra[];
  id: string;
  category_id: string;
  vendor_id: string;
  org_ind_type: string;
  creator_id: string;
  title: string;
  alias: string;
  created: string;
  modified: string;
  type: string;
  max_donors: string;
  minimum_amount: string;
  risk_per: string;
  short_description: string;
  long_description: string;
  goal_amount: string;
  paypal_email: string;
  first_name: string;
  last_name: string;
  address: string;
  address2: string;
  city: string;
  other_city: string;
  state: string;
  country: string;
  zip: string;
  phone: string;
  group_name: string;
  website_address: string;
  start_date: string;
  end_date: string;
  allow_exceed: string;
  allow_view_donations: string;
  published: string;
  internal_use: string;
  featured: string;
  js_groupid: string;
  success_status: string;
  processed_flag: string;
  video_on_details_page: string;
  allowed_countries?: null;
  meta_data: string;
  meta_desc: string;
  ordering: string;
  image: TImage;
  amount_received: number;
  remaining_amount: number;
  donor_count: string;
};

export type TImage = {
  id: string;
  title: string;
  type: string;
  path: string;
  state: string;
  source: string;
  original_filename: string;
  size: string;
  storage: string;
  created_by: string;
  access: string;
  created_date: string;
  params?: null[] | null;
  media: string;
  media_s: string;
  media_m: string;
  media_l: string;
};

export type TExtra = {
  field_id: string;
  value: string;
  type: string;
  name: string;
  label: string;
};
